apiVersion: v1
kind: Secret
metadata:
  name: pg-credentials
type: Opaque
stringData:
  username: postgres
  password: postgres
  dbname: customers
  # a connection string that can be directly referenced by the microservice
  url: postgresql://postgres:postgres@postgres:5432/customers
